spring:
  output:
    ansi:
      enabled: always
  datasource:
    driverClassName: org.postgresql.Driver
doma:
  jdbc-logger: SLF4J
  dialect: postgres
  naming: snake-lower-case
logging:
  file:
    path: logs
  charset:
    file: UTF-8
  logback:
    rollingpolicy:
      max-history: 30
